### ISSUE TITLE
DEVOPS-5: Fix SDK test failures — ERR_MODULE_NOT_FOUND for BankrollPool

### ISSUE THREAD

**Issue by n1ur0** [n1ur0/duckpools-coinflip#162]
## Problem

SDK Tests CI job fails consistently with:
```
ERR_MODULE_NOT_FOUND: Cannot find module 'sdk/dist/src/pool/BankrollPool'
ERR_UNSUPPORTED_DIR_IMPORT: Directory import 'sdk/dist/src/types' not supported
```

## Root Cause

The TypeScript SDK build output in `sdk/dist/` has ESM module resolution issues:
1. `BankrollPool.js` is missing from the build output (imported from `sdk/dist/src/pool/index.js`)
2. Barrel import `from '../types'` fails because Node ESM doesn't support directory imports without explicit `index.js`

## Impact

- CI is red on every PR (1 of 5 failures, now 1 of 2 after #161 fixed the other 3)
- Blocks PR merges if CI gates are tightened

## Suggested Fix

1. Check `sdk/tsconfig.json` — ensure `moduleResolution` is `node16` or `nodenext` and that all barrel exports include explicit `index.js`
2. Verify `sdk/package.json` has `"type": "module"` and `"exports"` map if using ESM
3. Check if `BankrollPool.ts` was recently renamed or moved without updating imports

## Labels

`junior`, `priority:P2`
